# ══════════════════════════════════════════════════════════════════════════════
# app/services/token_service.py
#
# Token economy layer for CogniLearn.
#
# Every student is allocated 1,000,000 tokens on signup. Each LLM call
# deducts the exact token count returned in the model's response metadata.
# Requests are blocked when tokens_remaining reaches 0.
#
# Invariant (enforced in Supabase):
#   tokens_remaining + tokens_used = 1,000,000 always.
#   Any deviation indicates an accounting bug.
#
# response.usage_metadata = {
#    "input_tokens":  int,   ← prompt sent to the model
#    "output_tokens": int,   ← response generated by the model
#    "total_tokens":  int,   ← input + output combined
# }
# ── How to use the @token_guard decorator ─────────────────────────────────────
#
#   Wrap any chain function that calls an LLM with @token_guard.
#   The decorator handles the full lifecycle automatically:
#     1. Checks tokens_remaining before the chain runs
#     2. Runs the chain if tokens are available
#     3. Reads the exact token count from the model's response metadata
#     4. Deducts from tokens_remaining, adds to tokens_used in Supabase
#
#   The wrapped function MUST:
#     - Accept student_id as its first argument
#     - Return a LangChain response object with usage_metadata attached
#
#   Example:
#       from app.services.token_service import token_guard
#
#       @token_guard
#       def run_qa_chain(student_id: str, query: str, store: Chroma):
#           ...
#           return chain.invoke({"query": query, "context": chunks})
#
#   The caller never changes — token logic is invisible to the router:
#       result = run_qa_chain(student_id="abc123", query="What is RISC?", store=store)
#
# ── UI Integration ─────────────────────────────────────────────────────────────
#
#   After each chain call, the router reads the updated tokens_remaining
#   from Supabase and passes it to the Jinja2 template context so the
#   UI always reflects the current balance without a separate API call.
#
#   Example in a router:
#       result = run_qa_chain(student_id=user["id"], query=query, store=store)
#       profile = get_learner_profile(user["id"])
#       return templates.TemplateResponse("chat.html", {
#           "request": request,
#           "response": result,
#           "tokens_remaining": profile["tokens_remaining"],
#       })
#
# ══════════════════════════════════════════════════════════════════════════════

import functools
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable


# ─────────────────────────────────────────────────────────────────────────────
# JSON PROFILE STORE (dev only — replaced by Supabase in production)
#
# Each student's learner profile is stored as a separate JSON file at:
#   data/profiles/{student_id}.json
#
# This mirrors the multi-user isolation of the Chroma vector store —
# one file per student, no cross-contamination.
#
# TODO: Remove this entire section when Supabase is integrated.
#       Replace with supabase_client queries in get_tokens_remaining()
#       and deduct_tokens() below.
# ─────────────────────────────────────────────────────────────────────────────

# Root directory for all learner profile JSON files
_PROFILES_DIR = Path(__file__).parent.parent.parent / "data" / "profiles"

# Default profile template — matches the agreed learner data structure
_DEFAULT_PROFILE = {
    "user_id": "",
    "learning_pace": "average",
    "tokens_remaining": 1_000_000,
    "tokens_used": 0,
    "token_history": [],  # append-only log of every LLM call
    "weak_topics": [],
    "strong_topics": [],
    "revision_dates": [],
    "topics": {},
}


def _get_profile_path(student_id: str) -> Path:
    """Returns the path to a student's JSON profile file."""
    if not student_id or not student_id.strip():
        raise ValueError("student_id cannot be empty or whitespace.")
    return _PROFILES_DIR / f"{student_id}.json"


def _load_profile(student_id: str) -> dict:
    """
    Load a student's JSON profile from disk.

    If the profile file does not exist, creates a new one from the
    default template with the student_id pre-filled. This mimics
    the 'create on signup' behaviour that Supabase will handle later.

    Args:
        student_id: Unique identifier for the student.

    Returns:
        Dict representing the student's full learner profile.

    Raises:
        RuntimeError: If the profile file exists but cannot be read
                      or contains malformed JSON.
    """
    profile_path = _get_profile_path(student_id)

    # Create the profiles directory if it doesn't exist yet
    _PROFILES_DIR.mkdir(parents=True, exist_ok=True)

    if not profile_path.exists():
        # First time this student is seen — create a fresh profile
        profile = {**_DEFAULT_PROFILE, "user_id": student_id}
        _save_profile(student_id, profile)
        print(f"  [token_service] New profile created for student: {student_id}")

    try:
        with open(profile_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        raise RuntimeError(
            f"Profile file for student '{student_id}' exists but contains "
            f"malformed JSON. File: {profile_path} | Error: {e}"
        ) from e
    except OSError as e:
        raise RuntimeError(
            f"Could not read profile file for student '{student_id}'. "
            f"File: {profile_path} | Error: {e}"
        ) from e


def _save_profile(student_id: str, profile: dict) -> None:
    """
    Persist a student's updated profile dict back to disk as JSON.

    Args:
        student_id: Unique identifier for the student.
        profile:    The full updated profile dict to save.

    Raises:
        RuntimeError: If the file cannot be written due to permission
                      or disk space issues.
    """
    profile_path = _get_profile_path(student_id)
    _PROFILES_DIR.mkdir(parents=True, exist_ok=True)

    try:
        with open(profile_path, "w", encoding="utf-8") as f:
            json.dump(profile, f, indent=2)
    except OSError as e:
        raise RuntimeError(
            f"Could not write profile file for student '{student_id}'. "
            f"File: {profile_path} | Error: {e}"
        ) from e


# ─────────────────────────────────────────────────────────────────────────────
# CUSTOM EXCEPTION
# ─────────────────────────────────────────────────────────────────────────────


class InsufficientTokensError(Exception):
    """
    Raised when a student's token balance has reached zero.

    Caught in the router layer and returned as a 402 HTTP response
    with a user-facing message. Never surfaces as a raw 500 error.

    Example:
        try:
            result = run_qa_chain(student_id=user["id"], ...)
        except InsufficientTokensError:
            return templates.TemplateResponse("errors/tokens_exhausted.html", ...)
    """

    pass


# ─────────────────────────────────────────────────────────────────────────────
# SUPABASE TOKEN OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────


def get_tokens_remaining(student_id: str) -> int:
    """
    Fetch the current token balance for a student.

    DEV: Reads from the student's JSON profile file in data/profiles/.
    TODO: Replace body with Supabase query when database layer is ready:
              from app.services.supabase_client import supabase
              response = (
                  supabase.table("Learner_Profiles")
                  .select("tokens_remaining")
                  .eq("student_id", student_id)
                  .single()
                  .execute()
              )
              return response.data["tokens_remaining"]

    Args:
        student_id: Unique identifier for the student.

    Returns:
        Integer token balance. Returns 0 if the student profile is
        not found to fail safely rather than grant unintended access.

    Raises:
        ValueError:   If student_id is empty or whitespace.
        RuntimeError: If the profile file cannot be read or is corrupt.
    """
    if not student_id or not student_id.strip():
        raise ValueError("student_id cannot be empty or whitespace.")

    # ── DEV: JSON file read — replace with Supabase query ────────────────────
    try:
        profile = _load_profile(student_id)
        remaining = profile.get("tokens_remaining", 0)
        print(f"  [token_service] Tokens remaining for '{student_id}': {remaining:,}")
        return remaining
    except RuntimeError:
        raise  # Re-raise with original context intact
    except Exception as e:
        print(
            f"  [token_service] ✗ Unexpected error reading profile for '{student_id}': {e}"
        )
        return 0  # Fail safely — deny access rather than grant it


def deduct_tokens(
    student_id: str,
    input_tokens: int,
    output_tokens: int,
    total_tokens: int,
    chain_name: str,
) -> dict:
    """
    Deduct consumed tokens from a student's balance and log the call.

    Decrements ``tokens_remaining`` and increments ``tokens_used``
    by ``total_tokens``, preserving the invariant:
        tokens_remaining + tokens_used = 1,000,000

    Appends a full record to ``token_history`` capturing the input/output
    breakdown, the chain that triggered the call, and a UTC timestamp.
    This provides a complete audit trail of every LLM call per student.

    DEV: Reads and writes the student's JSON profile file in data/profiles/.
    TODO: Replace body with a Supabase atomic RPC when database layer is ready:
              from app.services.supabase_client import supabase
              supabase.rpc("deduct_student_tokens", {
                  "p_student_id":   student_id,
                  "p_input_tokens": input_tokens,
                  "p_output_tokens": output_tokens,
                  "p_total_tokens": total_tokens,
                  "p_chain_name":   chain_name,
              }).execute()
          Note: In Supabase, token_history becomes a dedicated Token_History
          table (not a JSON column) so it can be queried efficiently at scale.
          See project documentation for the full schema.

    Args:
        student_id:    Unique identifier for the student.
        input_tokens:  Tokens consumed by the prompt sent to the model.
        output_tokens: Tokens consumed by the model's response.
        total_tokens:  input_tokens + output_tokens. This is the amount
                       deducted from tokens_remaining.
        chain_name:    Name of the chain function that triggered this call.
                       Retrieved from chain_func.__name__ in token_guard.

    Returns:
        Dict with updated balances:
        {
            "tokens_remaining": int,
            "tokens_used":      int,
            "tokens_this_call": int,
        }

    Raises:
        ValueError:   If student_id is empty or any token count is negative.
        RuntimeError: If the profile file cannot be read or written.
    """
    if not student_id or not student_id.strip():
        raise ValueError("student_id cannot be empty or whitespace.")

    if input_tokens < 0 or output_tokens < 0 or total_tokens < 0:
        raise ValueError(
            f"Token counts must be non-negative. "
            f"Got input={input_tokens}, output={output_tokens}, total={total_tokens}."
        )

    # ── DEV: JSON file update — replace with Supabase RPC ────────────────────
    try:
        profile = _load_profile(student_id)

        # Update flat balance fields in memory then write once
        profile["tokens_remaining"] = max(0, profile["tokens_remaining"] - total_tokens)
        profile["tokens_used"] = profile.get("tokens_used", 0) + total_tokens

        # Append this call's full breakdown to the history list
        history_entry = {
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "total_tokens": total_tokens,
            "chain": chain_name,
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S"),
        }
        profile.setdefault("token_history", []).append(history_entry)

        _save_profile(student_id, profile)

        print(
            f"  [token_service] Deducted {total_tokens:,} tokens — "
            f"student: '{student_id}' | chain: {chain_name} | "
            f"in: {input_tokens:,} | out: {output_tokens:,} | "
            f"remaining: {profile['tokens_remaining']:,}"
        )

        return {
            "tokens_remaining": profile["tokens_remaining"],
            "tokens_used": profile["tokens_used"],
            "tokens_this_call": total_tokens,
        }

    except (ValueError, RuntimeError):
        raise
    except Exception as e:
        raise RuntimeError(
            f"Unexpected error deducting tokens for student '{student_id}': {e}"
        ) from e


# ─────────────────────────────────────────────────────────────────────────────
# TOKEN GUARD DECORATOR
# ─────────────────────────────────────────────────────────────────────────────


def token_guard(chain_func: Callable) -> Callable:
    """
    Decorator — enforces the token economy around every LLM chain call.

    Wraps a chain function to automatically:
        1. Check the student's token balance before running
        2. Block the call and raise InsufficientTokensError if balance is 0
        3. Run the chain if tokens are available
        4. Read the exact token count from the model's response metadata
        5. Deduct tokens and log the transaction

    The wrapped function must:
        - Accept ``student_id`` as its FIRST positional or keyword argument
        - Return a LangChain response object that has ``usage_metadata``
          attached (all LangChain LLMs populate this automatically)

    ── Usage ──────────────────────────────────────────────────────────────────

    Decorating a chain function:

        from app.services.token_service import token_guard

        @token_guard
        def run_qa_chain(student_id: str, query: str, store: Chroma):
            # ... build and invoke chain ...
            return chain.invoke({"query": query, "context": chunks})

    Calling from a router (token logic is completely invisible):

        # In routers/chat.py
        try:
            result = run_qa_chain(
                student_id=current_user["id"],
                query=user_question,
                store=store,
            )
        except InsufficientTokensError:
            # Render a tokens-exhausted page or return a 402 response
            return templates.TemplateResponse("errors/tokens_exhausted.html", {
                "request": request,
            }, status_code=402)

    ── Token Count Source ──────────────────────────────────────────────────────

    LangChain populates ``usage_metadata`` on every LLM response:

        response.usage_metadata = {
            "input_tokens":  int,   ← tokens in the prompt
            "output_tokens": int,   ← tokens in the response
            "total_tokens":  int,   ← input + output (what we deduct)
        }

    We deduct ``total_tokens`` — the true cost of the call.

    Args:
        chain_func: The chain function to wrap. Must accept student_id
                    as its first argument and return a LangChain response.

    Returns:
        The wrapped function with identical signature to chain_func.

    Raises:
        InsufficientTokensError: If the student's token balance is 0.
        ValueError:              If the response has no usage_metadata
                                 (indicates the chain is not returning
                                  a proper LangChain response object).
    """

    @functools.wraps(chain_func)
    def wrapper(student_id: str, *args: Any, **kwargs: Any) -> Any:

        # ── Step 1: Check balance ─────────────────────────────────────────────
        remaining = get_tokens_remaining(student_id)

        print(
            f"  [token_guard] Checking tokens — student: {student_id} | remaining: {remaining} | chain: {chain_func.__name__}"
        )

        if remaining <= 0:
            print(f"  [token_guard] ✗ Token balance exhausted — student: {student_id}")
            raise InsufficientTokensError(
                f"Token balance exhausted for student '{student_id}'. "
                "Cannot process further LLM requests."
            )

        # ── Step 2: Run the chain ─────────────────────────────────────────────
        response = chain_func(student_id, *args, **kwargs)

        # ── Step 3: Extract token count from response metadata ────────────────
        usage = getattr(response, "usage_metadata", None)

        if usage is None:
            raise ValueError(
                f"{chain_func.__name__} did not return a LangChain response "
                "with usage_metadata. Ensure the chain returns the raw "
                "LLM response object, not a parsed or extracted value."
            )

        tokens_consumed = usage.get("total_tokens", 0)

        # ── Step 4: Deduct and print updated balance ──────────────────────────
        updated_balance = deduct_tokens(
            student_id=student_id,
            input_tokens=usage.get("input_tokens", 0),
            output_tokens=usage.get("output_tokens", 0),
            total_tokens=tokens_consumed,
            chain_name=chain_func.__name__,
        )

        print(
            f"  [token_guard] ✓ Tokens deducted — student: {student_id} | consumed: {tokens_consumed} | remaining: {updated_balance['tokens_remaining']}"
        )

        return response

    return wrapper
