# ══════════════════════════════════════════════════════════════════════════════
# app/services/token_service.py
#
# Token economy layer for CogniLearn.
#
# Every student is allocated 1,000,000 tokens on signup. Each LLM call
# deducts the exact token count returned in the model's response metadata.
# Requests are blocked when tokens_remaining reaches 0.
#
# Invariant (enforced in Supabase):
#   tokens_remaining + tokens_used = 1,000,000 always.
#   Any deviation indicates an accounting bug.
#
# response.usage_metadata = {
#    "input_tokens":  int,   ← prompt sent to the model
#    "output_tokens": int,   ← response generated by the model
#    "total_tokens":  int,   ← input + output combined
# }
# ── How to use the @token_guard decorator ─────────────────────────────────────
#
#   Wrap any chain function that calls an LLM with @token_guard.
#   The decorator handles the full lifecycle automatically:
#     1. Checks tokens_remaining before the chain runs
#     2. Runs the chain if tokens are available
#     3. Reads the exact token count from the model's response metadata
#     4. Deducts from tokens_remaining, adds to tokens_used in Supabase
#
#   The wrapped function MUST:
#     - Accept student_id as its first argument
#     - Return a LangChain response object with usage_metadata attached
#
#   Example:
#       from app.services.token_service import token_guard
#
#       @token_guard
#       def run_qa_chain(student_id: str, query: str, store: Chroma):
#           ...
#           return chain.invoke({"query": query, "context": chunks})
#
#   The caller never changes — token logic is invisible to the router:
#       result = run_qa_chain(student_id="abc123", query="What is RISC?", store=store)
#
# ── UI Integration ─────────────────────────────────────────────────────────────
#
#   After each chain call, the router reads the updated tokens_remaining
#   from Supabase and passes it to the Jinja2 template context so the
#   UI always reflects the current balance without a separate API call.
#
#   Example in a router:
#       result = run_qa_chain(student_id=user["id"], query=query, store=store)
#       profile = get_learner_profile(user["id"])
#       return templates.TemplateResponse("chat.html", {
#           "request": request,
#           "response": result,
#           "tokens_remaining": profile["tokens_remaining"],
#       })
#
# ══════════════════════════════════════════════════════════════════════════════

import functools
import json
import os
from pathlib import Path
from typing import Any, Callable


# ─────────────────────────────────────────────────────────────────────────────
# JSON PROFILE STORE (dev only — replaced by Supabase in production)
#
# Each student's learner profile is stored as a separate JSON file at:
#   data/profiles/{student_id}.json
#
# This mirrors the multi-user isolation of the Chroma vector store —
# one file per student, no cross-contamination.
#
# TODO: Remove this entire section when Supabase is integrated.
#       Replace with supabase_client queries in get_tokens_remaining()
#       and deduct_tokens() below.
# ─────────────────────────────────────────────────────────────────────────────

# Root directory for all learner profile JSON files
_PROFILES_DIR = Path(__file__).parent.parent.parent / "data" / "profiles"

# Default profile template — matches the agreed learner data structure
_DEFAULT_PROFILE = {
    "user_id": "",
    "learning_pace": "average",
    "tokens_remaining": 1_000_000,
    "tokens_used": 0,
    "weak_topics": [],
    "strong_topics": [],
    "revision_dates": [],
    "topics": {},
}


def _get_profile_path(student_id: str) -> Path:
    """Returns the path to a student's JSON profile file."""
    if not student_id or not student_id.strip():
        raise ValueError("student_id cannot be empty or whitespace.")
    return _PROFILES_DIR / f"{student_id}.json"


def _load_profile(student_id: str) -> dict:
    """
    Load a student's JSON profile from disk.

    If the profile file does not exist, creates a new one from the
    default template with the student_id pre-filled. This mimics
    the 'create on signup' behaviour that Supabase will handle later.

    Args:
        student_id: Unique identifier for the student.

    Returns:
        Dict representing the student's full learner profile.

    Raises:
        RuntimeError: If the profile file exists but cannot be read
                      or contains malformed JSON.
    """
    profile_path = _get_profile_path(student_id)

    # Create the profiles directory if it doesn't exist yet
    _PROFILES_DIR.mkdir(parents=True, exist_ok=True)

    if not profile_path.exists():
        # First time this student is seen — create a fresh profile
        profile = {**_DEFAULT_PROFILE, "user_id": student_id}
        _save_profile(student_id, profile)
        print(f"  [token_service] New profile created for student: {student_id}")

    try:
        with open(profile_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        raise RuntimeError(
            f"Profile file for student '{student_id}' exists but contains "
            f"malformed JSON. File: {profile_path} | Error: {e}"
        ) from e
    except OSError as e:
        raise RuntimeError(
            f"Could not read profile file for student '{student_id}'. "
            f"File: {profile_path} | Error: {e}"
        ) from e


def _save_profile(student_id: str, profile: dict) -> None:
    """
    Persist a student's updated profile dict back to disk as JSON.

    Args:
        student_id: Unique identifier for the student.
        profile:    The full updated profile dict to save.

    Raises:
        RuntimeError: If the file cannot be written due to permission
                      or disk space issues.
    """
    profile_path = _get_profile_path(student_id)
    _PROFILES_DIR.mkdir(parents=True, exist_ok=True)

    try:
        with open(profile_path, "w", encoding="utf-8") as f:
            json.dump(profile, f, indent=2)
    except OSError as e:
        raise RuntimeError(
            f"Could not write profile file for student '{student_id}'. "
            f"File: {profile_path} | Error: {e}"
        ) from e


# ─────────────────────────────────────────────────────────────────────────────
# CUSTOM EXCEPTION
# ─────────────────────────────────────────────────────────────────────────────


class InsufficientTokensError(Exception):
    """
    Raised when a student's token balance has reached zero.

    Caught in the router layer and returned as a 402 HTTP response
    with a user-facing message. Never surfaces as a raw 500 error.

    Example:
        try:
            result = run_qa_chain(student_id=user["id"], ...)
        except InsufficientTokensError:
            return templates.TemplateResponse("errors/tokens_exhausted.html", ...)
    """
    pass


# ─────────────────────────────────────────────────────────────────────────────
# SUPABASE TOKEN OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────


def get_tokens_remaining(student_id: str) -> int:
    """
    Fetch the current token balance for a student.

    DEV: Reads from the student's JSON profile file in data/profiles/.
    TODO: Replace body with Supabase query when database layer is ready:
              from app.services.supabase_client import supabase
              response = (
                  supabase.table("Learner_Profiles")
                  .select("tokens_remaining")
                  .eq("student_id", student_id)
                  .single()
                  .execute()
              )
              return response.data["tokens_remaining"]

    Args:
        student_id: Unique identifier for the student.

    Returns:
        Integer token balance. Returns 0 if the student profile is
        not found to fail safely rather than grant unintended access.

    Raises:
        ValueError:   If student_id is empty or whitespace.
        RuntimeError: If the profile file cannot be read or is corrupt.
    """
    if not student_id or not student_id.strip():
        raise ValueError("student_id cannot be empty or whitespace.")

    # ── DEV: JSON file read — replace with Supabase query ────────────────────
    try:
        profile = _load_profile(student_id)
        remaining = profile.get("tokens_remaining", 0)
        print(f"  [token_service] Tokens remaining for '{student_id}': {remaining:,}")
        return remaining
    except RuntimeError:
        raise  # Re-raise with original context intact
    except Exception as e:
        print(f"  [token_service] ✗ Unexpected error reading profile for '{student_id}': {e}")
        return 0  # Fail safely — deny access rather than grant it


def deduct_tokens(student_id: str, tokens_consumed: int) -> dict:
    """
    Deduct consumed tokens from a student's balance.

    Decrements ``tokens_remaining`` and increments ``tokens_used``
    by ``tokens_consumed``, preserving the invariant:
        tokens_remaining + tokens_used = 1,000,000

    DEV: Reads and writes the student's JSON profile file in data/profiles/.
    TODO: Replace body with a Supabase atomic RPC when database layer is ready:
              from app.services.supabase_client import supabase
              supabase.rpc("deduct_student_tokens", {
                  "p_student_id": student_id,
                  "p_tokens_consumed": tokens_consumed,
              }).execute()
          Note: Use a Supabase RPC (stored procedure) for the atomic
          decrement/increment to prevent race conditions on concurrent calls.

    Args:
        student_id:       Unique identifier for the student.
        tokens_consumed:  Exact token count from model response metadata.
                          Retrieved via response.usage_metadata["total_tokens"].
                          Must be a non-negative integer.

    Returns:
        Dict with updated balances:
        {
            "tokens_remaining":          int,
            "tokens_used":               int,
            "tokens_consumed_this_call": int,
        }

    Raises:
        ValueError:   If student_id is empty or tokens_consumed is negative.
        RuntimeError: If the profile file cannot be read or written.
    """
    if not student_id or not student_id.strip():
        raise ValueError("student_id cannot be empty or whitespace.")

    if tokens_consumed < 0:
        raise ValueError(
            f"tokens_consumed must be a non-negative integer. "
            f"Got: {tokens_consumed}"
        )

    # ── DEV: JSON file update — replace with Supabase RPC ────────────────────
    try:
        profile = _load_profile(student_id)

        # Update both fields in memory then write once — preserves invariant
        profile["tokens_remaining"] = max(0, profile["tokens_remaining"] - tokens_consumed)
        profile["tokens_used"] = profile.get("tokens_used", 0) + tokens_consumed

        _save_profile(student_id, profile)

        print(
            f"  [token_service] Deducted {tokens_consumed:,} tokens — "
            f"student: '{student_id}' | "
            f"remaining: {profile['tokens_remaining']:,} | "
            f"used: {profile['tokens_used']:,}"
        )

        return {
            "tokens_remaining": profile["tokens_remaining"],
            "tokens_used": profile["tokens_used"],
            "tokens_consumed_this_call": tokens_consumed,
        }

    except (ValueError, RuntimeError):
        raise  # Re-raise typed errors with original context intact
    except Exception as e:
        raise RuntimeError(
            f"Unexpected error deducting tokens for student '{student_id}': {e}"
        ) from e


# ─────────────────────────────────────────────────────────────────────────────
# TOKEN GUARD DECORATOR
# ─────────────────────────────────────────────────────────────────────────────


def token_guard(chain_func: Callable) -> Callable:
    """
    Decorator — enforces the token economy around every LLM chain call.

    Wraps a chain function to automatically:
        1. Check the student's token balance before running
        2. Block the call and raise InsufficientTokensError if balance is 0
        3. Run the chain if tokens are available
        4. Read the exact token count from the model's response metadata
        5. Deduct tokens and log the transaction

    The wrapped function must:
        - Accept ``student_id`` as its FIRST positional or keyword argument
        - Return a LangChain response object that has ``usage_metadata``
          attached (all LangChain LLMs populate this automatically)

    ── Usage ──────────────────────────────────────────────────────────────────

    Decorating a chain function:

        from app.services.token_service import token_guard

        @token_guard
        def run_qa_chain(student_id: str, query: str, store: Chroma):
            # ... build and invoke chain ...
            return chain.invoke({"query": query, "context": chunks})

    Calling from a router (token logic is completely invisible):

        # In routers/chat.py
        try:
            result = run_qa_chain(
                student_id=current_user["id"],
                query=user_question,
                store=store,
            )
        except InsufficientTokensError:
            # Render a tokens-exhausted page or return a 402 response
            return templates.TemplateResponse("errors/tokens_exhausted.html", {
                "request": request,
            }, status_code=402)

    ── Token Count Source ──────────────────────────────────────────────────────

    LangChain populates ``usage_metadata`` on every LLM response:

        response.usage_metadata = {
            "input_tokens":  int,   ← tokens in the prompt
            "output_tokens": int,   ← tokens in the response
            "total_tokens":  int,   ← input + output (what we deduct)
        }

    We deduct ``total_tokens`` — the true cost of the call.

    Args:
        chain_func: The chain function to wrap. Must accept student_id
                    as its first argument and return a LangChain response.

    Returns:
        The wrapped function with identical signature to chain_func.

    Raises:
        InsufficientTokensError: If the student's token balance is 0.
        ValueError:              If the response has no usage_metadata
                                 (indicates the chain is not returning
                                  a proper LangChain response object).
    """
    @functools.wraps(chain_func)
    def wrapper(student_id: str, *args: Any, **kwargs: Any) -> Any:

        # ── Step 1: Check balance ─────────────────────────────────────────────
        remaining = get_tokens_remaining(student_id)

        print(f"  [token_guard] Checking tokens — student: {student_id} | remaining: {remaining} | chain: {chain_func.__name__}")

        if remaining <= 0:
            print(f"  [token_guard] ✗ Token balance exhausted — student: {student_id}")
            raise InsufficientTokensError(
                f"Token balance exhausted for student '{student_id}'. "
                "Cannot process further LLM requests."
            )

        # ── Step 2: Run the chain ─────────────────────────────────────────────
        response = chain_func(student_id, *args, **kwargs)

        # ── Step 3: Extract token count from response metadata ────────────────
        usage = getattr(response, "usage_metadata", None)

        if usage is None:
            raise ValueError(
                f"{chain_func.__name__} did not return a LangChain response "
                "with usage_metadata. Ensure the chain returns the raw "
                "LLM response object, not a parsed or extracted value."
            )

        tokens_consumed = usage.get("total_tokens", 0)

        # ── Step 4: Deduct and print updated balance ──────────────────────────
        updated_balance = deduct_tokens(student_id, tokens_consumed)

        print(f"  [token_guard] ✓ Tokens deducted — student: {student_id} | consumed: {tokens_consumed} | remaining: {updated_balance['tokens_remaining']}")

        return response

    return wrapper